using System;
using System.Linq.Expressions;
using BuildUp.Utility.Reflection;

namespace BuildUp
{
	public static class GeneratorExtensions
	{
		/// <summary>
		/// Creates a new generator that modifies the sequence of objects by invoking a function against each object generated by
		/// this generator
		/// </summary>
		/// <param name="generator"> </param>
		/// <param name="selector"></param>
		/// <returns></returns>
		public static IGenerator<TResult> Select<TObject, TResult>(this IGenerator<TObject> generator, Func<TObject, TResult> selector)
		{
			return Generators.Create((context, obj) => selector(obj), generator);
		}

		/// <summary>
		/// Creates a new generator that modifies each object generated by this generator by executing the specified action.
		/// Intended for actions that mutate the objects
		/// </summary>
		/// <param name="generator"> </param>
		/// <param name="action"></param>
		/// <returns></returns>
		public static IGenerator<TObject> Select<TObject>(this IGenerator<TObject> generator, Action<TObject> action)
		{
			return Generators.Create((context, obj) => { 
				action(obj);
				return obj;
			}, generator);
		}

		/// <summary>
		/// Returns a new generator that takes each object generated by this generator and sets 
		/// the member specified by the expression to a given value
		/// </summary>
		/// <typeparam name="TObject"></typeparam>
		/// <typeparam name="TMember"></typeparam>
		/// <param name="generator"></param>
		/// <param name="expression"></param>
		/// <param name="value"></param>
		/// <returns></returns>
		public static IGenerator<TObject> Set<TObject,TMember>(this IGenerator<TObject> generator, Expression<Func<TObject,TMember>> expression, TMember value)
		{
			var accessor = MemberAccessor.For(expression);
			Action<TObject> set = x => accessor.SetValue(x, value);
			return generator.Select(set);
		}

		/// <summary>
		/// Returns a new generator that takes each object generated by the current generator and sets 
		/// the member specified by the expression to a value supplied by a different generator
		/// </summary>
		/// <typeparam name="TObject"></typeparam>
		/// <typeparam name="TMember"></typeparam>
		/// <param name="generator"></param>
		/// <param name="expression"></param>
		/// <param name="values"></param>
		/// <returns></returns>
		public static IGenerator<TObject> Set<TObject, TMember>(this IGenerator<TObject> generator, Expression<Func<TObject, TMember>> expression, IGenerator<TMember> values)
		{
			var accessor = MemberAccessor.For(expression);
			return generator.SelectMany(s => values, (@object, value) => accessor.SetValue(@object, value));
		}
	}
}