using System;
using System.Collections.Generic;

namespace BuildUp
{
	/// <summary>
	/// Provides a sequence of objects suitable for unit testing, test data generation etc
	/// </summary>
	/// <typeparam name="TObject"></typeparam>
	public interface ISource<TObject> : IEnumerable<TObject>
	{
		/// <summary>
		/// Creates a new source that provides a new sequence of objects by invoking a function against the items generated by this source
		/// </summary>
		/// <param name="select"></param>
		/// <returns></returns>
		ISource<TResult> Select<TResult>(Func<TObject,TResult> select);

		/// <summary>
		/// Creates a new source that provides a new sequence of objects by invoking an action against the items generated by this source
		/// </summary>
		/// <param name="action"></param>
		/// <returns></returns>
		ISource<TObject> Select(Action<TObject> action);

		
	}
}