using System;
using System.Collections;
using System.Collections.Generic;

namespace BuildUp
{
	public interface ISource
	{
		IEnumerable Build();
	}

	/// <summary>
	/// Generates a sequence of objects suitable for unit testing, test data generation etc
	/// </summary>
	/// <typeparam name="TObject"></typeparam>
	public interface ISource<TObject> : ISource
	{
		/// <summary>
		/// Generates the sequence of objects
		/// </summary>
		/// <returns></returns>
		new IEnumerable<TObject> Build();
		
		/// <summary>
		/// Creates a new source that generates a sequence of objects by invoking a function against each object generated by
		/// this source
		/// </summary>
		/// <param name="selector"></param>
		/// <returns></returns>
		ISource<TResult> Select<TResult>(Func<TObject,TResult> selector);

		/// <summary>
		/// Creates a new source that invokes the specified action aginst each object generated by this source
		/// </summary>
		/// <param name="action"></param>
		/// <returns></returns>
		ISource<TObject> Select(Action<TObject> action);
				
		/// <summary>
		/// Creates a new source that combines the sequence of objects generated by this source with those from an additional sequence,
		/// then invokes the specified function on each pair of objects. The resulting sequence will be the length of the shortest sequence.
		/// </summary>
		/// <typeparam name="TChild"></typeparam>
		/// <typeparam name="TResult"></typeparam>
		/// <param name="sequenceSelector"></param>
		/// <param name="resultSelector"></param>
		/// <returns></returns>
		ISource<TResult> SelectMany<TChild, TResult>(Func<ISource<TObject>, ISource<TChild>> sequenceSelector, Func<TObject, TChild, TResult> resultSelector);

		/// <summary>
		/// Creates a new source that will combine the sequence of objects created by the current source with those from an additional sequence and 
		/// invokes the specified function on each pair of objects.
		/// </summary>
		/// <typeparam name="TChild"></typeparam>
		/// <param name="childSequenceSelector"></param>
		/// <param name="modify"></param>
		/// <returns></returns>
		ISource<TObject> SelectMany<TChild>(Func<ISource<TObject>, ISource<TChild>> childSequenceSelector, Action<TObject, TChild> modify);

		/// <summary>
		/// Creates a new source using the supplied function to modify the sequence of objects generated by the source
		/// </summary>
		/// <param name="modify"></param>
		/// <returns></returns>
		ISource<TObject> ModifySequence(Func<IEnumerable<object>, IEnumerable<object>> modify);

	}
}